### ISSUE TITLE
Help Wanted: Android build

### ISSUE THREAD

**Issue by rafcontreras** [vaxxnz/vaxxed-as-app#12]
I'm not an expert on Android Builds, I'm getting this error:

```
In file included from /Users/{user}/repos/new-app/VaxxedAs/node_modules/react-native-vision-camera/android/src/main/cpp/java-bindings/JHashMap.cpp:5:
/Users/{user}/repos/new-app/VaxxedAs/node_modules/react-native-vision-camera/android/src/main/cpp/java-bindings/JHashMap.h:16:8: error: redefinition of 'JHashMap'
```

`redefinition of 'JHashMap'`

I think it's the last hurdle to be able to get it into the GooglePlay Store.

**Comment by KevinSJ** [comment]
Hello @rafcontreras, I actually tried to built this on my Linux machine and it worked fine. So it could be the issue with your build machine. However, I doid have trouble running it on my phone -- oneplus 7 pro, getting the message shown in the screenshot.
![Screenshot_20211125-231122](https://user-images.githubusercontent.com/7546654/143425684-47b2f9d2-b48a-4117-a583-ac0b1c66fc7a.jpg)

**Comment by KevinSJ** [comment]
This issue is due to duplicate import in mainApplication.java, I created a pr to fix it, but the app can run on my phone now

**Comment by rafcontreras** [comment]
That is awesome @KevinSJ! I will take a look at your PR
